name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Vet
      run: go vet

    - uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: "2021.1.2"

    - name: Test
      run: go test -v ./...
